server.port=9090
google.speech.api.key=AIzaSyDTULZVCFtLRSqHwEDKH9VpLz8Va4VjAfw
google.speech.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
spring.main.web-application-type=servlet
